### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by StanGirard** [StanGirard/quivr#1]
### Stack End Goal:

- [ ] Python with FastAPI for the Backend
- [ ] NextJS for the WebAPP
- [ ] Electron + NextJS Desktop App

All future code will go toward this.

Looking for NextJS experts ;) 

### Vector Stores to implement:

- [ ] Weaviate
- [ ] Chromadb

### LLM support

- [ ] GPT4all
- [ ] Llama
- [ ] Whisper alternative

### Features
- [ ] Copy/Paste information #19 
- [ ] Training brain with its answers #16 
- [ ] Sources to output #11 
- [ ] Self Hosting LLM and Embeddings #5 
- [ ] History of answers #13 
- [ ] Zip Ingestion

**Comment by iyengarm** [comment]
can't get the dependency right from requirements.txt realtime-py needs websockets <10

**Comment by byronvoorbach** [comment]
Thinking about adding support for Weaviate? 😁

**Comment by Klaudioz** [comment]
For #1, maybe [pynecone](https://github.com/pynecone-io/pynecone) is a good alternative.

**Comment by StanGirard** [comment]
@Klaudioz @byronvoorbach 

pynecone yes !
Weaviate if it supports metadata yes.

It is fairly simple to add if you want to try

Update this line https://github.com/StanGirard/quiver/blob/f6e05975c3420eb1957e14881fc968d80dc0d92e/main.py#L20

```
vector_store = SupabaseVectorStore(supabase, embeddings, table_name="documents")
```

**Comment by byronvoorbach** [comment]
Weaviate definitely supports metadata and extensive filtering. Also hybrid search is a built-in feature. Plus all open source 😌 we’ll come with a PR!

**Comment by StanGirard** [comment]
@byronvoorbach Cool 😎 Looking forward to it. 

I've just updated the roadmap ;)

**Comment by Frostbite1536** [comment]
Would it be hard to add Anthropic support?

**Comment by StanGirard** [comment]
If it works with langchain no

**Comment by Shaunwei** [comment]
> Would it be hard to add Anthropic support?

@Frostbite1536 I have already added Anthropic support
