### ISSUE TITLE
UX Upload improvement

### ISSUE THREAD

**Issue by Chloeroumengas** [StanGirard/quivr#1220]
- [x] Drag and drop files => Open Modal 

- [x] Click paper clip => Open Modal 

- [x] Effect When you press paperclip => it slides all at once (flip arrière mamadzz)

- [x] Significantly reduce the drag and drop window

![Image](https://github.com/StanGirard/quivr/assets/138109838/53762666-49f5-4d5f-881c-b26dffb54432)

- [x] Add the upload cloud icone

- [x] You can always see the conversation behind but it's grayed out
- [x] Brain selected is empty when no brain selected before 

- [x] 4 documents per row and then move to the next row. 

- [x] The modal gets biggers when you add document lines (no scrowling into this section). 

- [x] Once you have selected a brain AND upload documents, the button "send to my brain" becomes purple. 

- [x] The user can drag and drop document anywhere in the upload section. Or click on the cloud to access to his finder. 

- [x] Delete the frame around the files 

- [x] Remove save buttons on public brains in subscribers view

![Image](https://github.com/StanGirard/quivr/assets/138109838/e744d821-524d-4aa7-a538-0e9953947018)
