### ISSUE TITLE
[Onboarding] 4b - AAUser, my onboarding is removed from Onboardings table whatever its status

### ISSUE THREAD

**Issue by mamadoudicko** [StanGirard/quivr#1385]
Epic https://github.com/StanGirard/quivr/issues/1151

**Functional:**

1. Users will exit the onboarding step after 7 days, regardless of their onboarding status.
2. The related onboarding entry is removed from the onboardings table.

**TODO List:**

1. Create a migration to add a `creation_time` column to the onboarding table.
2. Add a repository to eliminate onboardings from the onboarding table that have been present for more than 7 days.
3. Set up a daily cron job at 00:00 to delete onboardings created more than 7 days ago.
```typescript
# Import necessary modules
from celery import Celery
from celery.schedules import crontab

# Initialize Celery
app = Celery(
    'my_cron_app',
    broker='redis://localhost:6379/0',  # Update with your Redis URL
    backend='redis://localhost:6379/0'  # Update with your Redis URL
)

# Define your function to be called
def my_func_name():
    # Your function code here
    print("Running my_func_name at 00:00")

# Configure the Celery task to run at midnight
app.conf.beat_schedule = {
    'run-my-func-at-midnight': {
        'schedule': crontab(minute=0, hour=0),
        'args': (),  # Optional: Add arguments to your function here
    }
}

if __name__ == '__main__':
    app.start()

```

## Tests

1. Add to db an onboarding with creation_date more than 7 days
2. Call the function which remove onboardings
3. Check that the user no longer exist in onboarding table

**Validation Criteria:**

- [ ] Create a new account.
- [ ] Verify that you are in the onboarding stage.
- [ ] Return after 7 days to confirm that the associated onboarding has been deleted.
