### ISSUE TITLE
[Shareable brains] I can share brains

### ISSUE THREAD

**Issue by StanGirard** [StanGirard/quivr#400]
# The why

The shareable brain allows a user to share one or multiple brains they have built with others users. 
Then, other users can use these brains, interact with them and sometimes even modify them according to their rights. 

# The what

![Image](https://github.com/StanGirard/quivr/assets/138109838/fa96910e-7c5b-4d37-9556-00afb8c256d9)

**Add a user to a brain**
When users move their mouse over the name of one of their brains 

- [x] The bin and the 'share' icon appear. 

When the user clicks on the share icon : 

- [x] A popup is displayed with a list of people who have access to this brain and a search bar allowing new people to be added. 

1. Users type in the email address of the person with whom they want to share one of their brains
2. Users select their "guest" rights (reader or editor) 
3. Users will press the button "share". 

Once they press "share" : 

- [x] the popup closes 
- [x] the person is added as a brain user. 
- [x] The invited user receives an email to access the brain. 

Choosing someone's rights to a brain : 

- [x] #535

- [x] The creator can choose if someone is reader or editor :
- A reader can only use a brain 
- A creator can "add ressources" to the brains
- An administrator can "add ressources" and "delete ressources" of the brain

- [x] The creator can modify the rights of his guests

**Remove someone from a brain:** 

- [x] The creator can remove someone from a brain
 

## What are the validation criteria to validate this feature?

What are you going to test to validate this feature? What are the edge cases? How should the feature behave in case of error ? How should the feature behave in case of missing data ? Are there other specific behaviours that should be clarified?

## Should this feature be feature flagged?

# The how

## How are we going to code this feature?

![Image](https://github.com/StanGirard/quivr/assets/100568984/f5dff282-381f-409c-bfc2-3254d621613c)

### Backend setup 
- [] Access Control List
- [] Add new boolean column in users_brains with 'pending_acceptance' 
- [] Create 2 new endpoints : 
     - [] brains/{brain_id}/subscription: 
           - [] post -> for inviter to send subscriptions requests to user per email with special url (https://quivr.app/xxx/?inviation_brain_id=2342chjkcns)
           - [] put -> for invited to accept subscription
           - [] get  -> for invited
           - [] delete with optional query param being user_id 
     - [] brains/{brain_id}/access: 
           - [] get -> to get all the types of accesses to the brain

## Organization of the tickets: 
Fonctionnalité partage d'invitation:
```mermaid
graph
0 
1 -->4
2 -->3
3 -->4
```
Fonctionnalité parcours invité:
```mermaid
graph
5 --> 6
6 --> 7
```
Fontionnalité brain management/sharing: 

```mermaid
graph
8 --> 9
```
## Are there any technical decisions made that should be shared?

Did you make any ADR for this feature that should be shared and validated?

## What is preventing us from delivering this feature?

Are there functional dependencies? Are there métier dependencies? Are there internal teams that need to be consulted/need to validate

## What can the feature potentially break?
