### ISSUE TITLE
[Prompt Customization] AAUser, I can set my brain's prompt

### ISSUE THREAD

**Issue by gozineb** [StanGirard/quivr#479]
# The why

The custom prompt allow Quivr users to create personalized instructions, known as "prompts," for guiding the generative AI process. The goal is to : Enhance user control ans creativity and expand user engagement.

![Image](https://github.com/StanGirard/quivr/assets/138109838/8a270d55-f67a-43af-b77c-04815f3c20f1)

Why do we need this functionality?
What’s the value? For whom?

# The what

AAuser, when I go to the "settings tab" or when I click on the "create brain" on the "managing brain" page, I can see : 
- [ ] A custom prompt title that I can edit and save by clicking "enter"
- [ ] A text field where I can give instructions which will be used as the system instruction for the AI assistant. 
- [ ] After writing instructions, when I click on enter, my brain prompt is set. 
- [ ] The text field will support various prompt formats, such as plain text, questions etc 
- [ ] I can see A dropdown menu that shows differents personality that have been preset 
- [ ] Anytime I change anything (title, prompt description or selection of personality), I see a green popup to confirm my change. 

<img width="683" alt="image" src="https://github.com/StanGirard/quivr/assets/138109838/5ca12ad9-5a47-4b0d-82b6-a1b21b7e2d85">
<img width="353" alt="image" src="https://github.com/StanGirard/quivr/assets/138109838/ea3a9ee5-dcf5-4049-aad1-4ad85ac53324">

## What are we developing?

What’s the expected behaviour? How should it look like?

## What are the validation criteria to validate this feature?

What are you going to test to validate this feature? What are the edge cases? How should the feature behave in case of error ? How should the feature behave in case of missing data ? Are there other specific behaviours that should be clarified?

## Should this feature be feature flagged?

# The how

## How are we going to code this feature?

- [ ] Prompt market:
   - [ ] Create a table Prompts : id (UUID auto generated) + title + content  + status (public or private) (default to private for now)
   - [ ] Utils: add prompt, update prompt title or content, delete a prompt
   - [ ] Endpoint: get /prompt -> list of public prompts (title + content)
- [ ] Update brain Entity:
   - [ ] Table: add prompt_id column references prompt table 
   - [ ] Utils: get prompt_id from brain_id
   - [ ] Endpoints:
      - [ ] get: retrieve the prompt with brain_id -> prompt_id -> prompt table -> id + title + content
      - [ ] put endpoint -> create or update prompt with id + title + content
      - [ ] delete endpoint -> delete prompt from prompt_table if brain deleted (not just deleted from brains_users) and prompt is private
- [ ] BrainPrompt component: 
   - [ ] CustomPrompt: 
      - [ ]  title  + content
   - [ ] PromptMarket:
     - [ ]  DropDown:
       - [ ] fill with  get on /prompt: see title 
       - [ ] on click: set the title +content of the CustomPrompt with the clicked on prompt
    
Tickets:
1- AABE, I have a prompts table with a get endpoint
2- AABE, a brain can be created or updated with a prompt
3- AAU, I can create or update a brain with a prompt
4- AAU, I can pick one of the pre-existing public prompt from my brain
5- AAU, when I delete the brain I own, the prompt (if private) is also deleted from the database

## Are there any technical decisions made that should be shared?

Did you make any ADR for this feature that should be shared and validated?

## What is preventing us from delivering this feature?

Are there functional dependencies? Are there métier dependencies? Are there internal teams that need to be consulted/need to validate

**Comment by shivvamm** [comment]
can i work on it

**Comment by gozineb** [comment]
Sure @shivvamm,I was planning on starting this in 2 weeks but it would be great to have your contribution. 
The idea is to have in the frontend, a prompt text area where the user can enter his own personal prompt instead of the one that is currently injected in the backend. 
A custom prompt should be attached to a brain Entity. You will need to update the brains table too. 
Feel free to ping me if you want to discuss the tech strategy before starting working on it.

**Comment by shivvamm** [comment]
Yes aure i want to know about the details to approach this

**Comment by shivvamm** [comment]
Hi @gozineb , thank you for including me in this project. I'm excited to contribute! Before I start working on it, I would appreciate a follow-up discussion to clarify a few details and understand the tech strategy better. Could you please provide more information on how the frontend and backend are currently structured? Additionally, it would be helpful to know what technologies and frameworks are being used. This will allow me to plan my approach accordingly. Once I have a better understanding, I'll be ready to start working on implementing the feature. Please let me know how and when we can schedule a discussion. Thank you!

**Comment by gozineb** [comment]
Hi @shivvamm, thanks for your interesting in the project:
- Backend: fastapi + python + supabase (SQL)
- [] Custom prompts should be stored in the brain table: you would need to update the tables.sql and add a migration to include this new column
- [] add an endpoint to add/update the custom prompt in the brain : Post on /brain -> see 'router' and 'api' folder in backend
- [] add the custom prompt when the question is asked:    question_generator in QABaseBrainPicking and _construct_prompt in OpenAIFunctionsBrainPicking
- Fronted: next + react in typescript
- [] Add an area where prompt can be customized in front -> You could do that in the settings for now for example 
- [] Use the activeBrain to call endpoint to update prompt
- [] Add tests to your new components.

You can look take a look at how to contribute in the docs. We haven't fully detailed the backend and frontend architectures as it is still an on going work. Will get to that ASAP.

Don't hesitate to dive into the codebase & put your technical strategy here (even with your gray areas) and I will take the time to review it before you start :)

**Comment by shivvamm** [comment]
sure @gozineb  :)

**Comment by beifeng777** [comment]
想用中文回答问题，如何设置prompt模板？

**Comment by mj321** [comment]
Hi.

Just wanted to respond in order to show my support for this feature. I'm looking forward to this!

**Comment by gozineb** [comment]
Hi @shivvamm. have you started working on this ? If not, will be starting on this next week !

**Comment by shivvamm** [comment]
Hey @gozineb  I was going to start I was just thinking we have to separate the prompt make it a global entity and then edit it

**Comment by shivvamm** [comment]
@gozineb  I'll push the changes till tomorrow

**Comment by gozineb** [comment]
Hi @shivvamm, @mamadoudicko will start working on this today. Have you been able to push your PR ?

**Comment by kunalgoyal9** [comment]
Hi,
I think it has been added to main branch. I tried it, but seems like it doesn't work well. Can I increase weightage to this prompt? If I use system prompt standalone to openAI API, it works differently.

**Comment by gozineb** [comment]
Hi @kunalgoyal9, feel free to creatre an issue with the proposed change ! Thank you for your interest 😀
I will be closing this one as it is done.

**Comment by mj321** [comment]
Thanks to all who worked on this. Much appreciated.
