### ISSUE TITLE
[Brain management]

### ISSUE THREAD

**Issue by Chloeroumengas** [StanGirard/quivr#531]
# The why

-Manage brains settings : name, description, configuration
-Manage people: add, delete and modify people's rights. 
-Manage files : add and delete
For every brains

# The what

Overview : 

![Image](https://github.com/StanGirard/quivr/assets/138109838/d629350f-e34b-44ff-87e1-f7ad645062a5)

![Image](https://github.com/StanGirard/quivr/assets/138109838/ced2ff87-924b-49ed-85d2-e7d651c8dea3)

![Image](https://github.com/StanGirard/quivr/assets/138109838/96598f48-78c3-4322-9479-67853ef41f7a)

**TICKET 1** 

**1. As a user, when I click on the setting icon** : 

- [ ]  I am redirected to a page with a modal that list list all of my brains on the left

- [ ] When I arrive on the page, I arrive on my active brain. So the modal on the right shows the information linked to my active brain. 

Eg if my active brain is “sales team”.

![Image](https://github.com/StanGirard/quivr/assets/138109838/41229299-f818-4681-bd3a-03972d9a9b1a)

![Image](https://github.com/StanGirard/quivr/assets/138109838/f2c94e80-de5b-41e6-9c27-04e0a4b33407)

**2. The brain changes on click :**

- [ ] When I click on an other brain in the lists, the right modal shows informations for the new selected brain. 

- [ ] Visually, when I move my mouse over another brain in the list, it becomes a little darker and when I click on it (I select it), it changes colour from lilac to white.

- [ ] When I click on the search bar I can see a drop-down menu with my list of brains. 
- [ ] I can also start typing the name of a brain to find it. 
- [ ] I can select my brain by clicking on it and then pressing enter. 

**TICKET 2** 

As a user I can see and manage a list of informations concerning my selected brain on the right componant. 

- [ ] There are 3 tabs: settings, people and files. I automatically arrive on the settings page. 
Here I can: 

- [ ] I can edit my brain name by clicking on any letter of the brain name, changing it and press enter or click anywhere else.
- [ ] I can edit my brain descroption the same way 
- [ ] I can change my model configuration and create a new key the same way it was in the old version of settings.

![Image](https://github.com/StanGirard/quivr/assets/138109838/d36eea9d-d794-4259-8a27-3071f14f46b3)

- [ ] When I click on "people", I arrive on a page to manage people. 

- [ ]I can add members to my selected brain by typing their email address, select their right then click on share. 

- [ ] The user receive an invitation by mail. 

- [ ]When I click “enter” after typing an email address, a new row appears to add a new member 

- [ ] When I click the button “+”, a new row appears to add a new member. 

- [ ] Below, I can see a list of members and when I add a new members, a new row appears with the new members

- [ ] When I click on the bin, a popup appears “are you sure you want to delete this profile” and “yes” “no” to confirm removal. 

- [ ] When someone is deleted, he doesn’t have any access to the brain anymore and his name doesn’t appear on the list.

- [ ] I can change the members rights by clicking on editor or viewer : 

A viewer can : 

- Chat with the brain
- See docs

An editor can : 

- Chat with the brain
- See docs
- Download docs
- Share brain with other people
- Delete and upload files

![Image](https://github.com/StanGirard/quivr/assets/138109838/a9bc9333-1a2a-46b7-8d36-68c77911bdbd)

**TICKET 3** 

![Image](https://github.com/StanGirard/quivr/assets/138109838/182f38e3-e9f3-46a2-a02b-c5c8ae9bfab2)

- [ ] When I click on the download icon, the document is automatically downloaded. 

- [ ] I can edit my document’s name by clicking on any letter of the doc name, changing it and press enter or click anywhere else. 

- [ ] When I click on the bin, I can delete a doc.

# THE HOW

- [x] 1- AAUser, when I click on the temporary 'B' icon, i am redirect to a BrainsManagement page with my list of brains:
        - [x] Create a Temporary button in the navbar, on click, redirect to BrainsManagementPage 
        - [ ] BrainsListBar : on the left, in one column : BrainsList  (sort by brain name) + AddBrain + SearchForBrain (Same page ratio as chat)
- [ ] 2- AAUser, on the brainsManagementPage, i have 3 tabs in the layout:
        - [ ] BrainConfiguration
        - [ ] BrainUsers
        - [ ] BrainKnowledge
  
- [ ] 3- AABE, I can store/update brain configuration: 
        - [ ] Update brains table with: description, model, tokens, temperature, openAiKey
        - [ ] Update brain class + brains db calls
        - [ ] Update brain creation + update endpoint
        - [ ] 
- [ ] 4- AAUser, I have access to a settings tab to configure my brain:
        - [ ]  BrainConfiguration
- [ ] 5- AAUser, I can override the brain's settings in the chat -> related to a chat or a question ??:
        - [ ]  Add new modal: chatConfiguration -> should get opened on click on settings icon in chat area
        - [ ] Remove the configuration from the current overall settings page
        - [ ] update /chat ? /question endpoint

- [ ] 6 - AAUser. I have access to a people tab to see who has access to the brain and to share the brain:
        - [ ] BrainsUsersWithAccess list
        - [ ] ShareBrain component
- [ ] 7  - AABackend, when a knowledge is uploaded, it is stored and can be downloaded:
        - [ ] Use Supabase Storage to store file
        - [ ] Update /upload: store file, 
        - [ ] endooint to get uploaded knowledge + download
- [ ] 8 - AABackend, when a knowledge is crawled, the url is stored and can be retrieved 
         - [ ] Update /crawl: for website/github, store only url + embedded file size
         - [ ] endpoint to get crawled knowledge data
- [ ] 9 - AAUser, I have access to a Knowledge tab  listing my knowledge: 
         - [ ] For all knowledge, list: Date added, added by, type of knowledge, name, size, download/link
         - [ ] For files, ability to download
         - [ ] For crawls, replace download with link/access to url 
 - [ ] 10 - AAUser, I can add my own OpenAI API Key + get my Quivr API Key in the User page
         - [ ] Add API key config in User Page 
         - [ ] If brain API Key, use brain's. Else, if user's, use user's. Else use quivr's.
         - [ ] Move the Quivr API key config to user's page
         - [ ] Add a quick guide to Quivr's API key generation -> see issue #740 
- [ ] 11- AAUser, I can see the brains management icon in the navbar: 
         - [ ] Remove the settings page
         - [ ] Re-use the settings icon to accessBrainsManagement
         - [ ] Remove temporary icon from BrainManagement 

```mermaid
graph
1 --> 2
2 --> 4
3 --> 4
4 --> 5
2 --> 6
2--> 9
7 --> 9
8 --> 9
5 --> 11
10 --> 11
```
