### ISSUE TITLE
[Custom prompt] 

### ISSUE THREAD

**Issue by Chloeroumengas** [StanGirard/quivr#760]
# The why

The custom prompt allow Quivr users to create personalized instructions, known as "prompts," for guiding the generative AI process. The goal is to : Enhance user control ans creativity and expand user engagement.

![Image](https://github.com/StanGirard/quivr/assets/138109838/8a270d55-f67a-43af-b77c-04815f3c20f1)

Why do we need this functionality?
What’s the value? For whom?

# The what

AAuser, when I go to the "settings tab" or when I click on the "create brain" on the "managing brain" page, I can see : 
- [ ] A custom prompt title that I can edit and save by clicking "enter"
- [ ] A text field where I can give instructions which will be used as the system instruction for the AI assistant. 
- [ ] After writing instructions, when I click on enter, my brain prompt is set. 
- [ ] The text field will support various prompt formats, such as plain text, questions etc 
- [ ] I can see A dropdown menu that shows differents personality that have been preset 
- [ ] Anytime I change anything (title, prompt description or selection of personality), I see a green popup to confirm my change. 

<img width="683" alt="image" src="https://github.com/StanGirard/quivr/assets/138109838/5ca12ad9-5a47-4b0d-82b6-a1b21b7e2d85">
<img width="353" alt="image" src="https://github.com/StanGirard/quivr/assets/138109838/ea3a9ee5-dcf5-4049-aad1-4ad85ac53324">

## What are we developing?

What’s the expected behaviour? How should it look like?

## What are the validation criteria to validate this feature?

What are you going to test to validate this feature? What are the edge cases? How should the feature behave in case of error ? How should the feature behave in case of missing data ? Are there other specific behaviours that should be clarified?

## Should this feature be feature flagged?

# The how

## How are we going to code this feature?

What’s the technical strategy to deliver? What are the impacts on the architecture diagram? What could be the unexpected consequences of the feature on other parts of the code? Could there be other technical edge cases?

## Are there any technical decisions made that should be shared?

Did you make any ADR for this feature that should be shared and validated?

## What is preventing us from delivering this feature?

Are there functional dependencies? Are there métier dependencies? Are there internal teams that need to be consulted/need to validate
