### ISSUE TITLE
[UX Chloé] V2 - Chat

### ISSUE THREAD

**Issue by Chloeroumengas** [StanGirard/quivr#778]
# The why

The Chat is the Homepage of Quivr. It is an intuitive, simple, and minimalist interface that serves as the focal point for all Quivr's functionalities. Everything can be made from this single place.

![Image](https://github.com/StanGirard/quivr/assets/100568984/8820acf4-d36a-4ff5-acb2-8e40c8f4176f)
![Image](https://github.com/StanGirard/quivr/assets/100568984/0006c54c-ab3e-40a5-ba0d-5c3c156dfc5e)

# The what

In Quivr, we have no more than just the chat as the central element. And two icons at the top right: "brain management" and "users."

![Image](https://github.com/StanGirard/quivr/assets/100568984/c77805aa-b863-401f-b385-fadb271bf107)

**HOME PAGE FIRST TIME**

AAUser, when I arrive on the homepage (chat) **for the first time** I can see :

- [ ]  An empty screen with the keyboard shortcuts written (see image ⇒ Same design)
- These are non clickable
- They will disappear as soon as I ask my first question (I have written a question and then type enter)
- This screen will reappear anytime if I press “commande K”

**QUESTION BAR** 

- [ ]  A question bar to talk with my brains, files and choose a prompt.

![Image](https://github.com/StanGirard/quivr/assets/100568984/5b79596e-055b-44fa-a9c2-a493c1b94c0c)

    
- The question bar have a placeholder saying ‘ask a question to “@ brains of / files and choose a # prompt”
- If I click on the question bar, the place holder disappear.
- I can write a question and then press enter.
- When I press enter, the question is in the chat and I can see the placeholder in the question bar reappear
- The question bar has a floating design with light shadows
- The question bar has 2 buttons : the “+” for knwoledge upload on the left and the wheel on the right

---

**QUESTION BAR BEHAVIOUR** 

- [ ]  AAUser, I can talk with my brains / files and choose a prompt in the “question bar” questions :

![Image](https://github.com/StanGirard/quivr/assets/100568984/b163c959-0e76-4098-9d1e-6108668c97e9)
![Image](https://github.com/StanGirard/quivr/assets/100568984/d62b295d-3550-4ad6-a757-79ddffa04cd2)
![Image](https://github.com/StanGirard/quivr/assets/100568984/21143c57-4c63-48ee-a9c6-8bbeb5865c53)

- When I click @, I can see the list of all my existing brains and a button “create new brain”. Same when I click on / for files or # for prompt.

![Image](https://github.com/StanGirard/quivr/assets/100568984/d255e06d-6b58-4e99-885f-db0088c8d202)

- If I select a brain, I can see it’s added in my question bar. I can then write a question and the answer will be made by the brain. Same for files and prompt
    

![Image](https://github.com/StanGirard/quivr/assets/100568984/7ad1e192-190d-491b-92ac-00923f9dd66e)

    
- I can see that the brain I chose is written above every question and answers related to this brain, in grey. Same for files and prompt
- Anytime I want to ask a new question, the previous brain, prompt and files I chosed are still tagged in the question bar.

![Image](https://github.com/StanGirard/quivr/assets/100568984/86c9d6b9-784d-46d7-828b-63dd9c4d833f)

- If I click on the “minus” it will make the brain/ files or prompt disappear from my question bar.

![Image](https://github.com/StanGirard/quivr/assets/100568984/737a4544-75b5-4277-8f89-44646f42b880)

- If I click on “create a new brain”, I can see the popup to create a brain appears. And this brain will be automatically selected in the question bar.

![Image](https://github.com/StanGirard/quivr/assets/100568984/bd0e39f2-5c72-4823-90a9-963b5dc2477a)

- If I click on the “share” icone, the popup share appears and I can share the brain with people.
- If I click on “add new files” I am redirected to the manage brains page on the “knowledge tab from this brain
- If I click on “create new prompt” I am redirected the manage brains page on the “settings” tab

**NO BRAIN** 

- [ ]  AAUser, if I ask a question without selecting a brain in the question bar **for the first time :**

![Image](https://github.com/StanGirard/quivr/assets/100568984/37efa526-4a0c-4789-8449-6429679cc5ee)

- The tag in grey is “@Universe”
- I have a message in blue centered in the page saying “You are now asking a question to the universe. To select a brain, type @ in the question bar and write your question”
- and then there is the answer from the Universe after this message

- [ ]  AAUser, if I ask a question without selecting a brain **but it’s not the first time**, I just have a “brainless mode” (see image)

**Other**

- [ ]  AAUser, when I arrive on the homepage (chat) for the second time, if I already used the chat, I can see my previous conversations.
- [ ]  AAUser, I can see the chat design is the same as in the images (light purple for brains, grey for me, full screen, whatsapp style, simple, minimalist)
![Image](https://github.com/StanGirard/quivr/assets/100568984/10c42fdb-5db2-4455-9730-72ba8665e33b)

# The How

AAU, when I arrive on a fresh chat, I have a new UI:
- Dialogue: AAU, I can see keyboard shortcuts as a placeholder for the empty dialog
- QuestionBar: 
	- New place holder message
	- See the selected brain 
	- AAU, when I click on '+' in the question bar, I am redirected to upload page
	- Upload page has a "chat", on click on that or on "x" -> modal is closed and we get back to the selected chat

AAU, when I am chatting, i have a new UI for the dialog:
- AAU, when I chat, I can see the selected brain in the dialog + in the question bar
- UI of the dialog: position + colors + see brain/prompt 

AAU, i can select a brain in the question bar: 
- AAU, i have an error message when no brain is selected (will change next)
- AAU, i can set a brain in the question: 
- AAU, i can delete the already selected brain

AAU, I can chat without a brain: 
	- AABE, I can answer without a brain
	- AAU, i can ask a question without selecting a brain
	- AAU, i can remove a brain and ask question without it

AAU, i can select a prompt in the question bar: 
- AABE, the prompt from the question can override the brain prompt 
- AAU, i can set a prompt in the question
- AAU, i can delete the already selected prompt

AAU, while the files are being uploaded, i can still use the app and get a notification

**Comment by gozineb** [comment]
Duplicate epic #779
