### ISSUE TITLE
[UX knowledge upload]

### ISSUE THREAD

**Issue by Chloeroumengas** [StanGirard/quivr#849]
# The why

The Knowledge upload is a functionality available in the question bar in the chat (main page) that allow user to feed their brain with files without having to move elsewhere. 

![Image](https://github.com/StanGirard/quivr/assets/138109838/806622c1-5ff5-4589-841c-97ae412500a8)

![Image](https://github.com/StanGirard/quivr/assets/138109838/3564ce16-56ae-43f2-8adf-b82b62bb1f48)

AAUser, when I am in the chat, and I press the “plus button” in the question bar, I can see : 

- [ ] The conversation in the chat turning to grey, non clickable anymore. 
- [ ] A "drag and drop" modal appears. It looks like it's sliding from the question bar.
- [ ] The question bar changing placeholder with "Choose which @brain(s) you want to feed with these files". No more plus button, and the wheel replaced by a sending icone. 

![Image](https://github.com/StanGirard/quivr/assets/138109838/1e45179a-82cf-4865-b0ce-8148db79cbcd)

- [ ] AAUser, when I drag a document in the "drag and drop" area, I can see an icone is created. 

![Image](https://github.com/StanGirard/quivr/assets/138109838/40cc10ac-cd17-45cb-8b7a-f6c950bf107f)

- [ ] AAUser, when I type a website URL in the area and I press "enter" I can see an icone is created. 

- [ ] If I upload files without typing a brain : notification error "you have to choose a brain". 

- [ ] If I type a brain without typing a file : notification error "you have to upload a file or website URL". 

- [ ]If I press "cross" the drag and drop modal is closing with the same effect has she came (sliding) and we back to the question bar.

- [ ] AAUser, If I chose at least 1 file and 1 brain and I press "enter" : 

- The drag and drop modal is closing with the same effect as she came (sliding). 
- I am back to the chat, with the question bar. 
- I can see an icone loading to the right of my question bar until my files will be uploaded to my brain 

![Image](https://github.com/StanGirard/quivr/assets/138109838/b081ed2d-3844-44c3-8d5b-5fcec63ae668)

Once all of the files are uploaded to the brain : 

https://files.slack.com/files-pri/T7RNRLR3P-F05RFJF7MTN/image.png

- I can see a "files" notification and line to notifying "the name of the brain" was fed. 

- [ ] AAUser, I can see a notification in red anytime files are not supported, or there is an error. 

https://files.slack.com/files-pri/T7RNRLR3P-F05RFJF7MTN/image.png

# The How

1- AAUser, I can feed a brain with knowledge from the ChatBar:
Feature flag: on click on '+' redirect towards /upload page
1.a: AAUser, when I click on the plus button, the input composant in the ChatBar is turned into an input bar to enter the brain to feed
Takes @ brain + submit button -> sends a /upload knowledge
1.b AAUser, when I click on the plus button, on top of the new input bar, I can see the old upload component in a closable modal 

2- AAUser, I see a modal with a new UX to feed a brain with knowledge: 
2.a AAUser, I can crawl a URL with a new UX
2.b AAUser, I can upload a file with a new UX by clicking on enter or by clicking on the send in the FeedBrainCommandBar
2.c AAUser, when I submit to feed a brain, the modal is closed and I can use the chat again
Remove feature flag (keep publish)
3- AABE, I can store notifications for brain feeding (success & failure)
3.a - AABE, I can store notifications for brain feeding (success & failure)
3.b - AABE, I send chat with its messages and notifications

4- AAUser, when my brain is being fed, I see an explicit message that it is in progress
5- AAUser, when my brain is done being fed, I can see the notification about the status in the chat dialogue
Dep: Backend/Frontend : how to get the notification it's done ? 
6- AAContributor, I update the documentation concerning brain feeding 
7- AAUser, upon login I get to the /chat page and on the left side of the navbar, I only see the quivr logo 
Dep: put explore in Knowledge tab in the brain settings

**Comment by gozineb** [comment]
Updated visuals:

Upload page open:
![Image](https://github.com/StanGirard/quivr/assets/100568984/6949264c-c302-4bed-8c55-febb53cca530)

**Comment by gozineb** [comment]
How to know if the chat we currently arrived on is currently loading my knowledge to my brain ?
- 1/ Notifications table: datetime, chat_id, message (Nullable), action (UPLOAD_KNOWLEDGE), status (Pending, Done)
- Modify the /upload and /crawl: 
- At start, create notification: with message = null, datetime, action and status Pending
- At end, update datetime and status as Done and the message 
- 2/ Add a route in the backend: takes a chat_id and returns
